/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Pranav9' at '13/9/15 3:17 PM' with Gradle 2.0
 *
 * @author Pranav9, @date 13/9/15 3:17 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
